version: '3.8'

services:
  fastapi:
    image: fastapi-app:latest
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      PORT: 8080
    ports:
      - 8081:8080
      
  angular:
    image: angular-app:latest
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: ./client
